spring.application.name=testMOUYoussifi
#spring.datasource.url=jdbc:h2:mem:patient-db
spring.h2.console.enabled=true
#pour changer de port
#server.port:8082
#spring.jpa.show-sql=true

#spring.datasource.url=jdbc:mysql://localhost/test
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=dbuser
spring.datasource.password=dbpass
#pour changer de port
server.port:8082
spring.jpa.show-sql=true

