# Nom de l'application
spring.application.name=testMOUYoussifi

# Connexion SQL Server sans SSL
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=dbuserthymleaf;encrypt=false
spring.datasource.username=dbuser
spring.datasource.password={myPass;word}  # Correction : pas de double "}}"

# Configuration JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Port du serveur
server.port=8082
