spring.application.name=testMOUYoussifi
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=dbuserthymleaf;encrypt=false
spring.datasource.username=dbuserYoussou
spring.datasource.password={myPass;word}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.properties.hebernete.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto =create





